version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: moviehub-postgres
    environment:
      POSTGRES_DB: moviehub
      POSTGRES_USER: moviehub
      POSTGRES_PASSWORD: moviehub123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moviehub-network

  redis:
    image: redis:7-alpine
    container_name: moviehub-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - moviehub-network

  app:
    build: .
    container_name: moviehub-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/moviehub
      - SPRING_DATASOURCE_USERNAME=moviehub
      - SPRING_DATASOURCE_PASSWORD=moviehub123
      - SPRING_REDIS_HOST=redis
      - TMDB_API_KEY=${TMDB_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
      - redis
    networks:
      - moviehub-network
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
  redis_data:

networks:
  moviehub-network:
    driver: bridge
